### ISSUE TITLE
Extract not working within a `rule`

### ISSUE THREAD

**Issue by AzizZayed** [egraphs-good/egglog#403]
Given these types and functions:
```lisp
(datatype Dimension
    (UnknownDim)
    (Dim i64)
)

(function idim (Dimension) i64)
(rule
	((Dim i))
 	((set (idim (Dim i)) i))
)

(datatype Shape
   (Shape2D Dimension Dimension)
)

(function nrows (Shape) Dimension)
(function ncols (Shape) Dimension)
(rewrite (nrows (Shape2D ?r ?z)) ?r)
(rewrite (ncols (Shape2D ?r ?z)) ?z)

(datatype MatOp
   (Mat String Shape)
   (MatMul MatOp MatOp Shape)
)

(function get_shape (MatOp) Shape)
(rewrite (get_shape (Mat ?n ?s)) ?s)
(rewrite (get_shape (MatMul ?x ?y ?s)) ?s)
   
(let mx (Mat "x" (Shape2D (Dim 5) (Dim 10)))) ; a*b = 5*10
(let my (Mat "y" (Shape2D (Dim 10) (Dim 15)))) ; b*c = 10*15
(let mz (Mat "z" (Shape2D (Dim 15) (Dim 2)))) ; c*d = 15*2

(let mxy (MatMul mx my (Shape2D (Dim 5) (Dim 15))))
(let myz (MatMul my mz (Shape2D (Dim 10) (Dim 2))))
```

The `extract` action is not working within this rule:

```lisp
(rule
    ((= ?lhs (MatMul ?x ?y (Shape2D ?a ?c)))
     (= ?sy (ncols (get_shape ?y))))
    ((extract ?sy))
)

(run 100)
```

The output is simply blank. Which I assume means the lhs was not found in the egraph and thus no match occurred. However the following rule works:

```lisp
(rule
    ((= ?lhs (MatMul ?x ?y (Shape2D ?a ?c))))
    ((extract ?c))
)

(run 100)
```

I'm assuming this means that the rule can't find `(ncols (get_shape ?y))` however, I want `(= ?sy (ncols (get_shape ?y)))` to be like calling a function to retrieve the number of columns in `?y`. What is going on here?

**Comment by saulshanabrook** [comment]
Yes the second example should work you posted. Let can appear in an action but not in a fact.

**Comment by AzizZayed** [comment]
How come this does not work:

```lisp
(rule
    ((= ?lhs (MatMul ?x ?y (Shape2D ?a ?c))))
    ((let b (ncols (get_shape ?y))) )
)
```

I get the error in the console:

anicked at src/lib.rs:1039:37:
error while running actions for (rule ((= ?lhs (MatMul ?x ?y (Shape2D ?a ?c))))
      ((let b (ncols (get_shape ?y))))
         ): Not found: No value found for ncols [Value { tag: "Shape", bits: 15 }]

Stack:

Error
    at imports.wbg.__wbg_new_abda76e883ba8a5f (https://egraphs-good.github.io/egglog/web_demo.js:339:21)
    at https://egraphs-good.github.io/egglog/web_demo_bg.wasm:wasm-function[1592]:0x150048
    at https://egraphs-good.github.io/egglog/web_demo_bg.wasm:wasm-function[864]:0x13953a
    at https://egraphs-good.github.io/egglog/web_demo_bg.wasm:wasm-function[1274]:0x14a566
    at https://egraphs-good.github.io/egglog/web_demo_bg.wasm:wasm-function[55]:0x74c7e
    at https://egraphs-good.github.io/egglog/web_demo_bg.wasm:wasm-function[31]:0x49b1d
    at https://egraphs-good.github.io/egglog/web_demo_bg.wasm:wasm-function[31]:0x48ae5
    at https://egraphs-good.github.io/egglog/web_demo_bg.wasm:wasm-function[20]:0x1fc7d
    at https://egraphs-good.github.io/egglog/web_demo_bg.wasm:wasm-function[33]:0x4d4f9
    at __exports.run_program (https://egraphs-good.github.io/egglog/web_demo.js:193:22)

**Comment by saulshanabrook** [comment]
If you have a function with a custom merge function, as you do here, then it won't have a default value... You can set a custom default value with `:default <...>`. With the default merge function then the default value is like an empty equivalence class.

Sorry that is the most confusing part of egglog and even after understanding it, it isn't particularly intuitive.

Basically just any function that has a custom merge function without a default or a function that returns a primitive must be set explicitly to a value instead of being just requested without a value being set first.

**Comment by oflatt** [comment]
Note that `default` is being removed in egglog soon! It's too confusing.

**Comment by Alex-Fischman** [comment]
Closing as resolved.
